### ISSUE TITLE
TypeError: Caught TypeError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by xinzheng798** [chenzhaiyu/points2poly#15]
(point2poly) [lilonghui_liujing@gpu01 points2poly]$ python reconstruct.py dataset_name='helsinki_mini' model_name='helsinki_fullview'
/share/home/lilonghui/lilonghui_liujing/zhengxin/environment/anaconda3/envs/point2poly/lib/python3.9/site-packages/sklearn/utils/multiclass.py:14: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
  from scipy.sparse.base import spmatrix
/share/home/lilonghui/lilonghui_liujing/zhengxin/environment/anaconda3/envs/point2poly/lib/python3.9/site-packages/sklearn/utils/optimize.py:18: DeprecationWarning: Please use `line_search_wolfe2` from the `scipy.optimize` namespace, the `scipy.optimize.linesearch` namespace is deprecated.
  from scipy.optimize.linesearch import line_search_wolfe2, line_search_wolfe1
/share/home/lilonghui/lilonghui_liujing/zhengxin/environment/anaconda3/envs/point2poly/lib/python3.9/site-packages/sklearn/utils/optimize.py:18: DeprecationWarning: Please use `line_search_wolfe1` from the `scipy.optimize` namespace, the `scipy.optimize.linesearch` namespace is deprecated.
  from scipy.optimize.linesearch import line_search_wolfe2, line_search_wolfe1
[2023-07-04 09:36:53,885][root][INFO] - processing /share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/datasets/helsinki_mini/06_vertex_group/5.vg
[2023-07-04 09:36:54,723][root][INFO] - refining planar primitives
[2023-07-04 09:36:54,732][root][INFO] - 8 pairs of planes merged
[2023-07-04 09:36:54,732][root][INFO] - prioritising planar primitives
[2023-07-04 09:36:54,733][root][INFO] - constructing cell complex
100%|███████████████████████████████████████████████████████████████████████████████| 23/23 [00:01<00:00, 12.46it/s]
[2023-07-04 09:36:56,581][root][INFO] - cell complex constructed: 1.85 s
[2023-07-04 09:36:56,581][root][INFO] - number of planes: 23
[2023-07-04 09:36:56,581][root][INFO] - number of cells: 129
[2023-07-04 09:36:56,718][root][INFO] - processing /share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/datasets/helsinki_mini/06_vertex_group/4.vg
[2023-07-04 09:36:56,796][root][INFO] - refining planar primitives
[2023-07-04 09:36:56,804][root][INFO] - 8 pairs of planes merged
[2023-07-04 09:36:56,804][root][INFO] - prioritising planar primitives
[2023-07-04 09:36:56,805][root][INFO] - constructing cell complex
100%|███████████████████████████████████████████████████████████████████████████████| 27/27 [00:03<00:00,  6.80it/s]
[2023-07-04 09:37:00,778][root][INFO] - cell complex constructed: 3.97 s
[2023-07-04 09:37:00,779][root][INFO] - number of planes: 27
[2023-07-04 09:37:00,804][root][INFO] - number of cells: 235
[2023-07-04 09:37:00,960][root][INFO] - processing /share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/datasets/helsinki_mini/06_vertex_group/6.vg
[2023-07-04 09:37:01,037][root][INFO] - refining planar primitives
[2023-07-04 09:37:01,073][root][INFO] - 34 pairs of planes merged
[2023-07-04 09:37:01,073][root][INFO] - prioritising planar primitives
[2023-07-04 09:37:01,076][root][INFO] - constructing cell complex
100%|███████████████████████████████████████████████████████████████████████████████| 53/53 [00:06<00:00,  8.21it/s]
[2023-07-04 09:37:07,530][root][INFO] - cell complex constructed: 6.45 s
[2023-07-04 09:37:07,530][root][INFO] - number of planes: 53
[2023-07-04 09:37:07,530][root][INFO] - number of cells: 387
[2023-07-04 09:37:07,680][root][INFO] - processing /share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/datasets/helsinki_mini/06_vertex_group/3.vg
[2023-07-04 09:37:07,756][root][INFO] - refining planar primitives
[2023-07-04 09:37:07,786][root][INFO] - 24 pairs of planes merged
[2023-07-04 09:37:07,786][root][INFO] - prioritising planar primitives
[2023-07-04 09:37:07,788][root][INFO] - constructing cell complex
100%|███████████████████████████████████████████████████████████████████████████████| 31/31 [00:02<00:00, 14.68it/s]
[2023-07-04 09:37:09,901][root][INFO] - cell complex constructed: 2.11 s
[2023-07-04 09:37:09,901][root][INFO] - number of planes: 31
[2023-07-04 09:37:09,901][root][INFO] - number of cells: 116
[2023-07-04 09:37:10,020][root][INFO] - processing /share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/datasets/helsinki_mini/06_vertex_group/2.vg
[2023-07-04 09:37:10,113][root][INFO] - refining planar primitives
[2023-07-04 09:37:10,144][root][INFO] - 22 pairs of planes merged
[2023-07-04 09:37:10,144][root][INFO] - prioritising planar primitives
[2023-07-04 09:37:10,146][root][INFO] - constructing cell complex
100%|███████████████████████████████████████████████████████████████████████████████| 35/35 [00:02<00:00, 17.20it/s]
[2023-07-04 09:37:12,182][root][INFO] - cell complex constructed: 2.04 s
[2023-07-04 09:37:12,183][root][INFO] - number of planes: 35
[2023-07-04 09:37:12,183][root][INFO] - number of cells: 130
[2023-07-04 09:37:12,263][root][INFO] - processing /share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/datasets/helsinki_mini/06_vertex_group/1.vg
[2023-07-04 09:37:12,299][root][INFO] - refining planar primitives
[2023-07-04 09:37:12,307][root][INFO] - 12 pairs of planes merged
[2023-07-04 09:37:12,307][root][INFO] - prioritising planar primitives
[2023-07-04 09:37:12,308][root][INFO] - constructing cell complex
100%|███████████████████████████████████████████████████████████████████████████████| 15/15 [00:01<00:00, 14.48it/s]
[2023-07-04 09:37:13,344][root][INFO] - cell complex constructed: 1.04 s
[2023-07-04 09:37:13,344][root][INFO] - number of planes: 15
[2023-07-04 09:37:13,344][root][INFO] - number of cells: 78
evaluating on dataset helsinki_mini
Random Seed: 40938661
getting information for 6 shapes
evaluating 1075 patches
  0%|                                                                                         | 0/6 [00:00<?, ?it/s]Warning: imp_surf_dist_ms must be converted to float32
Warning: imp_surf_dist_ms must be converted to float32
Warning: imp_surf_dist_ms must be converted to float32
Warning: imp_surf_dist_ms must be converted to float32
Warning: imp_surf_dist_ms must be converted to float32
Warning: imp_surf_dist_ms must be converted to float32
  0%|                                                                                         | 0/6 [00:00<?, ?it/s]
Error executing job with overrides: ['dataset_name=helsinki_mini', 'model_name=helsinki_fullview']
Traceback (most recent call last):
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/reconstruct.py", line 71, in reconstruct_full
    infer_sdf(cfg)
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/utils.py", line 166, in infer_sdf
    points_to_surf_eval.points_to_surf_eval(cfg)
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/points2surf/source/points_to_surf_eval.py", line 358, in points_to_surf_eval
    for batch_data in tqdm(dataloader):
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/environment/anaconda3/envs/point2poly/lib/python3.9/site-packages/tqdm/std.py", line 1176, in __iter__
    for obj in iterable:
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/environment/anaconda3/envs/point2poly/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/environment/anaconda3/envs/point2poly/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/environment/anaconda3/envs/point2poly/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/environment/anaconda3/envs/point2poly/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/environment/anaconda3/envs/point2poly/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/environment/anaconda3/envs/point2poly/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/environment/anaconda3/envs/point2poly/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/points2surf/source/data_loader.py", line 359, in __getitem__
    get_patch_points(shape=shape, query_point=imp_surf_query_point_ms)
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/points2surf/source/data_loader.py", line 335, in get_patch_points
    patch_pts_ids = point_cloud.get_patch_kdtree(
  File "/share/home/lilonghui/lilonghui_liujing/zhengxin/points2poly/points2surf/source/base/point_cloud.py", line 174, in get_patch_kdtree
    pts_dists_ms, patch_pts_ids = kdtree.query(x=query_point, k=points_per_patch, n_jobs=n_jobs)
  File "_ckdtree.pyx", line 786, in scipy.spatial._ckdtree.cKDTree.query
  File "_ckdtree.pyx", line 388, in scipy.spatial._ckdtree.get_num_workers
TypeError: Unexpected keyword argument {'n_jobs': 1}

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by chenzhaiyu** [comment]
New versions of `scipy.spatial._ckdtree.cKDTree.query()` have deprecated `n_jobs` for `workers`.
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.query.html

**Comment by omarsamiranov** [comment]
Thanks! @chenzhaiyu
