### ISSUE TITLE
from sage.all import polytopes, QQ, RR, Polyhedron  

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [chenzhaiyu/points2poly#24]
Do I need to install sage? sage looks so big.

(myria3d) root@e7c988bbfef7:/data/points2poly# python reconstruct.py dataset_name='helsinki_mini' model_name='helsinki_fullview'
Traceback (most recent call last):
  File "/data/points2poly/reconstruct.py", line 29, in <module>
    from utils import create_cell_complex, create_query_points, extract_surface, infer_sdf
  File "/data/points2poly/utils.py", line 14, in <module>
    from abspy import VertexGroup, CellComplex, AdjacencyGraph
  File "/root/miniconda3/envs/myria3d/lib/python3.9/site-packages/abspy/__init__.py", line 5, in <module>
    from .complex import *
  File "/root/miniconda3/envs/myria3d/lib/python3.9/site-packages/abspy/complex.py", line 28, in <module>
    from sage.all import polytopes, QQ, RR, Polyhedron
ModuleNotFoundError: No module named 'sage'
(myria3d) root@e7c988bbfef7:/data/points2poly#

**Comment by liuyunxa** [comment]
Hello, I have encountered the same problem as you. How did you solve it?
